# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 527ffc4763993f4377b257bd9959f7c496d6c9ed891b28cb9e16db8b67db295cdc15ffd980dc39266c1e7db5f6b74be62e66e99177c62b7540ec3776473b4edd

test:
  secret_key_base: c5ec3aa44a6c5fa6f0670c4f305344e38f70055953bb31bd95ef949d78f6d34493a07ab4b0f9c83cd2e55d4c433fcbdd4bba2eb201d35e01f8a6eeea40e8e04e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
